### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by l-vo**
Add tests which mainly cover my previous PR.

### CODE REVIEW

**Comment by mpasternak** [comment]
Looks good to me. I'd use Python 3.5 maybe and change the name of the test environment so it says "pep8" specifically. Thanks @l-vo .

**Comment by l-vo** [comment]
I'm not sure if I fully understand. Are some changes needed ?

**Comment by l-vo** [comment]
I'm sorry to raise you but will this PR be merged ? Also the package on pypi.org wasn't updated with my last update; is it normal ? Thanks in advance for your answers.

**Comment by mpasternak** [comment]
Committed, thanks!

**Comment by mpasternak** [comment]
About pypi release I’m not sure, I think @jpic may have privileges required

**Comment by l-vo** [comment]
@mpasternak thank you :)

**Comment by l-vo** [comment]
@jpic could you update the pypi package please ? Without that my PRs are useless for me :)

**Pull request merged**
